oppslag:
  kjoretoy:
    base-url: http://vegvesen
#    base-url: http://localhost:8060












## Erstatt linje 3 med http://localhost:8060 istedenfor.
#   Fasit:
#
# oppslag:
#   kjoretoy:
#     base-url: http://localhost:8060
