oppslag:
  kjoretoy:
    base-url: http://localhost:8060
  person:
    base-url: http://skatteetaten
bomregistrering:
  automatisk-krav: true
  bompasseringer-ikke-kronologisk-fikset: false # Oppgave 8
