server:
  servlet:
    context-path: /api
  error:
    include-message: always
spring:
  profiles:
    active: del2  # Her kan du bytte mellom profil del1 eller del2. Husk å kjøre ned og opp bomsystemet!
