server:
  servlet:
    context-path: /api
jackson:
  default-property-inclusion: non-absent
  mapper:
      accept-case-insensitive-enums: true
      accept-case-insensitive-properties: true
    deserialization:
      read-unknown-enum-values-using-default-value: true
      accept-single-value-as-array: true
      fail-on-unknown-properties: true
    serialization:
      write-empty-json-arrays: false
      fail-on-empty-beans: false
