oppslag:
  kjoretoy:
    base-url: http://localhost:8060
  person:
    base-url: http://localhost:8060
bomregistrering:
  automatisk-krav: true
  bompasseringer-ikke-kronologisk-fikset: false # for Oppgave 8, sett denne til true
